#!/usr/bin/env bash
# A bash script that prints all running processes in a consistent forma
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"
# List all processes, sorted by PPID
ps -eo user,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,cmd --sort=ppid
