#!/usr/bin/env bash
# A script that stops the 4-to_infinity_and_beyond process
PID=$(pgrep -f "./4-to_infinity_and_beyond")
if [ -n "$PID" ]; then
  echo "Stopping process with PID: $PID"
  kill "$PID"
else
  echo "No 4-to_infinity_and_beyond process found."
fi
